StarbucksDatabase/Models/Merchandise.cs
using System;
namespace StarbucksDatabase.Models
{
	public class Merchandise
	{
		public Merchandise()
		{
		}
		public int MerchandiseID { get; set; }
		public string MerchandiseName { get; set; }
		public string MerchandiseCategory { get; set; }
		public decimal MerchandisePrice { get; set; }
		public int MerchandiseSold { get; set; }
       

    }
}

StarbucksDatabase/Controllers/MerchandiseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StarbucksDatabase;
using StarbucksDatabase.Models;

namespace Testing.Controllers
{
    public class MerchandiseController : Controller
    {
        private readonly IMerchandiseRepository repo;

        public MerchandiseController(IMerchandiseRepository repo)
        {
            this.repo = repo;
        }


        public IActionResult Index()
        {
            var merchandise = repo.GetAllMerchandise();
            return View(merchandise);
        }
        public IActionResult ViewMerchandise(int id)
        {
            var merchandise = repo.GetMerchandise(id);
            return View(merchandise);
        }
        public IActionResult UpdateMerchandise(int id)
        {
            var merchandise = repo.GetMerchandise(id);
            if (merchandise == null)
            {
                return View("MerchandiseNotFound");
            }
            return View(merchandise);
        }
        public IActionResult UpdateMerchandiseToDatabase(Merchandise merchandise)
        {
            repo.UpdateMerchandise(merchandise);

            return RedirectToAction("ViewMerchandise", new { id = merchandise.MerchandiseID });
        }
        public IActionResult InsertMerchandise()
        {
            var merchandise = new Merchandise();
            return View(merchandise);
        }
        public IActionResult InsertMerchandiseToDatabase(Merchandise MerchandiseToInsert)
        {
            repo.InsertMerchandise(MerchandiseToInsert);
            return RedirectToAction("Index");
        }
        public IActionResult DeleteMerchandise(Merchandise merchandise)
        {
            repo.DeleteMerchandise(merchandise);
            return RedirectToAction("Index");
        }


    }
}

StarbucksDatabase/Views/Merchandise/Index.cshtml
@model IEnumerable<Merchandise>

<h2 class="colorChange">Products</h2>
<table class="tableColor">
    <div style="display: block">
        <a href="/Beverages/InsertBeverages/">Create a New Merchandise</a>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Category</th>
        <th>Price</th>
        <th>Sold</th>
    </tr>

    @foreach (var merchandise in @Model)
    {
        <tr>

            <td><a href=/Merchandise/ViewMerchandise/@merchandise.MerchandiseID>@merchandise.MerchandiseID</a></td>
            <td>@merchandise.MerchandiseName</td>
            <td>@merchandise.MerchandiseCategory</td>
            <td>@merchandise.MerchandisePrice</td>
            <td>@merchandise.MerchandiseSold</td>

        </tr>
    }

</table>
<div style="display: block">
    <a href="/Merchandise/InsertMerchandise/">Create a New Merchandise</a>
</div>
<video id="video-bg" autoplay muted loop>
    <source src="@Url.Content("~/Media/Merchandise.mp4")" type="video/mp4">
    Your browser does not support the video tag.
</video>

StarbucksDatabase/Views/Merchandise/InsertMerchandise.cshtml
@model Merchandise

<h2>Create a New Merchandise</h2>

@using (Html.BeginForm("InsertMerchandiseToDatabase", "Merchandise", "Post"))
{
    <input asp-for="MerchandiseID" type="hidden" value="" />

    <label asp-for="MerchandiseName" class="control-label">Name</label>
    <input type="text" name="MerchandiseName" class="form-control" value="" />

    <label asp-for="MerchandiseCategory" class="control-label">Category</label>
    <input type="text" name="MerchandiseCategory" class="form-control" value="" />

    <label asp-for="MerchandisePrice" class="control-label">Price</label>
    <input type="number" step="0.01" name="MerchandisePrice" class="form-control" />

    <label asp-for="MerchandiseSold" class="control-label">Sold</label>
    <input type="number" step="0.01" name="MerchandiseSold" class="form-control" />

    <input type="submit" value="Create Merchandise" class="btn btn-primary" />
}

StarbucksDatabase/Views/Merchandise/UpdateMerchandise.cshtml
@model Merchandise

<h2>Update @Model.MerchandiseName</h2>


@using (Html.BeginForm("UpdateMerchandiseToDatabase", "Merchandise", "Post"))
{
    <input asp-for="MerchandiseID" type="hidden" value="@Model.MerchandiseID" />

    <label asp-for="MerchandiseName" class="control-label">Name</label>
    <input type="text" name="MerchandiseName" class="form-control" value="@Model.MerchandiseName" />

    <label asp-for="MerchandiseCategory" class="control-label">Category</label>
    <input type="text" name="MerchandiseCategory" class="form-control" value="@Model.MerchandiseCategory" />

    <label asp-for="MerchandisePrice" class="control-label">Price</label>
    <input type="number" step="0.01" name="MerchandisePrice" class="form-control" value="@Model.MerchandisePrice" />

    <label asp-for="MerchandiseSold" class="control-label">Sold</label>
    <input type="number" step="0.01" name="MerchandiseSold" class="form-control" value="@Model.MerchandiseSold" />

    <input type="submit" value="Update Merchandise" class="btn btn-primary" />
}

StarbucksDatabase/Views/Merchandise/ViewMerchandise.cshtml
@model Merchandise

<h3>@Model.MerchandiseName Information</h3>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Category ID</th>
        <th>Price</th>
        <th>Sold</th>
    </tr>
    <tr>
        <td>@Model.MerchandiseID</td>
        <td>@Model.MerchandiseName</td>
        <td>@Model.MerchandiseCategory</td>
        <td>@Model.MerchandisePrice</td>
        <td>@Model.MerchandiseSold</td>
    </tr>
</table>
<div style="display: block">
    <a href="/Merchandise/UpdateMerchandise/@Model.MerchandiseID">Update this Merchandise</a>
</div>
<div style="display: block">

    @using (Html.BeginForm("DeleteMerchandise", "Merchandise", "Post"))
    {
        <input type="hidden" asp-for="MerchandiseID" value="@Model.MerchandiseID" />
        <input type="submit" onclick="return confirm('Are you sure?')" value="Delete this merchandise" />
    }
</div>